# Generated by Django 3.1.1 on 2020-09-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20200926_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='allowed_time',
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
