# Generated by Django 3.1.1 on 2020-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_auto_20200927_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
