# Generated by Django 3.1.1 on 2020-10-14 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_auto_20200928_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='completion_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 23, 27, 20, 543391)),
        ),
    ]
