# Generated by Django 3.1.1 on 2020-09-26 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('college_name', models.CharField(choices=[('Bhilai Institute Of Technology, Durg', 'Bhilai Institute Of Technology, Durg'), ('National Institute of Technology, Raipur', 'National Institute of Technology, Raipur'), ('Sankracharya Institute of Technology, Bhilai', 'Sankracharya Institute of Technology, Bhilai'), ('other', 'other')], default='other', max_length=512)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('CSE', 'CSE'), ('MECH', 'MECH'), ('ETC', 'ETC'), ('EE', 'EE'), ('CHE', 'CHE'), ('CIVIL', 'CIVIL'), ('MCA', 'MCA'), ('OTHER', 'OTHER')], default='OTHER', max_length=5)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('completed_profile', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
